namespace RandomVideoCallWebpage.Services;

public static class CountryCodes
{
    private static readonly Dictionary<string, string> Map = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Afghanistan"] = "AF",
        ["Albania"] = "AL",
        ["Algeria"] = "DZ",
        ["Argentina"] = "AR",
        ["Australia"] = "AU",
        ["Austria"] = "AT",
        ["Bangladesh"] = "BD",
        ["Belgium"] = "BE",
        ["Brazil"] = "BR",
        ["Bulgaria"] = "BG",
        ["Canada"] = "CA",
        ["Chile"] = "CL",
        ["China"] = "CN",
        ["Colombia"] = "CO",
        ["Croatia"] = "HR",
        ["Czech Republic"] = "CZ",
        ["Denmark"] = "DK",
        ["Egypt"] = "EG",
        ["Ethiopia"] = "ET",
        ["Finland"] = "FI",
        ["France"] = "FR",
        ["Germany"] = "DE",
        ["Greece"] = "GR",
        ["Hong Kong"] = "HK",
        ["Hungary"] = "HU",
        ["India"] = "IN",
        ["Indonesia"] = "ID",
        ["Iran"] = "IR",
        ["Iraq"] = "IQ",
        ["Ireland"] = "IE",
        ["Israel"] = "IL",
        ["Italy"] = "IT",
        ["Japan"] = "JP",
        ["Kenya"] = "KE",
        ["Malaysia"] = "MY",
        ["Mexico"] = "MX",
        ["Morocco"] = "MA",
        ["Nepal"] = "NP",
        ["Netherlands"] = "NL",
        ["New Zealand"] = "NZ",
        ["Nigeria"] = "NG",
        ["Norway"] = "NO",
        ["Pakistan"] = "PK",
        ["Philippines"] = "PH",
        ["Poland"] = "PL",
        ["Portugal"] = "PT",
        ["Romania"] = "RO",
        ["Russia"] = "RU",
        ["Saudi Arabia"] = "SA",
        ["Singapore"] = "SG",
        ["South Africa"] = "ZA",
        ["South Korea"] = "KR",
        ["Spain"] = "ES",
        ["Sri Lanka"] = "LK",
        ["Sweden"] = "SE",
        ["Switzerland"] = "CH",
        ["Taiwan"] = "TW",
        ["Thailand"] = "TH",
        ["Turkey"] = "TR",
        ["Ukraine"] = "UA",
        ["United Arab Emirates"] = "AE",
        ["United Kingdom"] = "GB",
        ["United States"] = "US",
        ["Vietnam"] = "VN",
        ["Other"] = "XX"
    };

    public static string GetCode(string country) =>
        Map.TryGetValue(country.Trim(), out var code) ? code : "XX";
}
